scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: range_filter
      type: laser_filters/LaserScanRangeFilter
      params:
        use_message_range_limits: false
        lower_threshold: 0.2
        upper_threshold: 5.0
        lower_replacement_value: .NaN
        upper_replacement_value: .NaN
    
    filter2:
      name: angle_block_1
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -0.119467787  # -6.845 degrees
        upper_angle: 0.119467787   # +6.845 degrees
    
    filter3:
      name: angle_block_2
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 0.328907      # +18.845 degrees
        upper_angle: 0.503963      # +28.915 degrees
    
    filter4:
      name: angle_block_3
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: 2.142915      # +122.8 degrees
        upper_angle: 2.465452      # +141.2 degrees
    
    filter5:
      name: angle_block_4
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -0.503963     # -28.915 degrees
        upper_angle: -0.328907     # -18.845 degrees
    
    filter6:
      name: angle_block_5
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -2.465452     # -141.2 degrees
        upper_angle: -2.142915     # -122.8 degrees